spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: book_info
          uri: http://localhost:8001/
          predicates:
            - Path=/books/**
        - id: recipe_book
          uri: http://localhost:8002/
          predicates:
            - Path=/recipe/**

server:
  port: 8000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/