spring:
  application:
    name: sem05_homework
  datasource:
    url: jdbc:postgresql://localhost:5432/homework_05
    username: ilya-devel
    password: some_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
