spring:
    application:
        name: sem11_homework
    datasource:
        url: jdbc:postgresql://localhost:5432/sem11_homework
        username: ilya-devel
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true

management:
    endpoints:
        web:
            exposure:
                # include: env, info, health
                include: metrics, prometheus, health
                # include: "*"
    endpoint:
        health:
            show-details: always